# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-paginate
    - jekyll-sitemap

# File rules
exclude: [vendor, Dangerfile, Gemfile, Gemfile.lock, LICENSE, README.md, assets/, package.json, yarn.lock, scripts/]
include: [.htaccess]
keep_files: [.well-known]

# Site
permalink: /blog/:title/
img_url: /img

# Metadata
title: 'Jesse Squires'
description: 'Turing complete with a stack of 0xdeadbeef'
url: https://www.jessesquires.com
logo: /ico/logo.png
timezone: America/Los_Angeles

# Author
author:
    name: 'Jesse Squires'
    twitter: jesse_squires
    avatar: /ico/avatar.jpg

# Setup
paginate_path: /blog/page/:num/
excerpt_separator: <!--excerpt-->

# Data
links:
    github: 'https://github.com/jessesquires/jessesquires.com'
    issue: 'https://github.com/jessesquires/jessesquires.com/issues/new'
    pull: 'https://github.com/jessesquires/jessesquires.com/compare'

social_links:
    twitter: 'https://twitter.com/jesse_squires'
    github: 'https://github.com/jessesquires/'
    stackoverflow: 'https://stackoverflow.com/users/2195632/jessesquires'
    keybase: 'https://keybase.io/jsq'
    applenews: 'https://apple.news/Td_gVU2BDSS2oPbz_sD150w'
