# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
   input: GFM
   syntax_highlighter: rouge

gems: [jekyll-sitemap, jekyll-paginate, jekyll-seo-tag]

exclude: [vendor]

# Permalinks
permalink: /:title/

# Site
title: 'Jesse Squires'
description: 'Turing complete with a stack of 0xdeadbeef'
url: http://www.jessesquires.com
logo: /img/logo.png
timezone: America/Los_Angeles

twitter:
  username: jesse_squires

img_url: http://www.jessesquires.com/img
# img_url: /img

# Author
author:
  name: 'Jesse Squires'
  twitter: jesse_squires

# Setup
paginate: 4
excerpt_separator: <!--excerpt-->

# Data
links:
  github: 'https://github.com/jessesquires/jessesquires.github.io'
  issue: 'https://github.com/jessesquires/jessesquires.github.io/issues/new'
  pull: 'https://github.com/jessesquires/jessesquires.github.io/compare'

social_links:
  twitter: 'https://twitter.com/jesse_squires'
  github: 'https://github.com/jessesquires/'
  linkedin: 'https://www.linkedin.com/in/jessesquires'
