# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: 'Jesse Squires'
tagline: 'Software developer in San Francisco'
timezone: America/Los_Angeles

paginate: 1
