# Dependencies
markdown: kramdown

kramdown:
    input: GFM
    syntax_highlighter: rouge

gems:
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-sitemap

exclude: [vendor, Dangerfile, Gemfile, Gemfile.lock, LICENSE, README.md, bower.json, scripts/]
include: [.htaccess]

keep_files: [.well-known]

# Permalinks
permalink: /blog/:title/

# Site
title: 'Jesse Squires'
description: 'Turing complete with a stack of 0xdeadbeef'
url: https://www.jessesquires.com
logo: /img/logo.png
timezone: America/Los_Angeles

twitter:
    username: jesse_squires

img_url: /img

# Author
author:
    name: 'Jesse Squires'
    twitter: jesse_squires

# Setup
paginate: 4
excerpt_separator: <!--excerpt-->

# Data
links:
    github: 'https://github.com/jessesquires/jessesquires.com'
    issue: 'https://github.com/jessesquires/jessesquires.com/issues/new'
    pull: 'https://github.com/jessesquires/jessesquires.com/compare'

social_links:
    twitter: 'https://twitter.com/jesse_squires'
    github: 'https://github.com/jessesquires/'
    linkedin: 'https://www.linkedin.com/in/jessesquires'
    applenews: 'https://apple.news/Td_gVU2BDSS2oPbz_sD150w'
    paypal: 'https://www.paypal.me/jessesquires'
    square: 'https://cash.me/$jsq'
    coinbase: 'https://www.coinbase.com/jsq'
