# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
   input: GFM
   syntax_highlighter: rouge

gems: [jekyll-sitemap, jekyll-paginate]

exclude: [vendor]

# Permalinks
permalink: /:title/

# Setup
title: 'Jesse Squires'
tagline: 'Turing complete with a stack of 0xdeadbeef'
timezone: America/Los_Angeles

url: http://www.jessesquires.com

author:
  name: 'Jesse Squires'
  handle: '@jesse_squires'
  twitter: 'https://twitter.com/jesse_squires'
  github: 'https://github.com/jessesquires/'
  linkedin: 'https://www.linkedin.com/in/jessesquires'

paginate: 4

excerpt_separator: <!--excerpt-->

links:
   github: 'https://github.com/jessesquires/jessesquires.github.io'
   issue: 'https://github.com/jessesquires/jessesquires.github.io/issues/new'
   pull: 'https://github.com/jessesquires/jessesquires.github.io/compare'
