# Dependencies
markdown: redcarpet
highlighter: pygments

gems:
  - jekyll-sitemap

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "superscript"]

# Permalinks
permalink: /:title/

# Setup
title: 'Jesse Squires'
tagline: 'Turing complete with a stack of 0xdeadbeef'
timezone: America/Los_Angeles

url: http://www.jessesquires.com

author:
  name: 'Jesse Squires'
  handle: '@jesse_squires'
  twitter: 'https://twitter.com/jesse_squires'
  github: 'https://github.com/jessesquires/'
  linkedin: 'https://www.linkedin.com/in/jessesquires'

paginate: 4

excerpt_separator: <!--excerpt-->

links:
   github: 'https://github.com/jessesquires/jessesquires.github.io'
   issue: 'https://github.com/jessesquires/jessesquires.github.io/issues/new'
   pull: 'https://github.com/jessesquires/jessesquires.github.io/compare'
