# Dependencies
markdown: redcarpet
highlighter: pygments

gems:
  - jekyll-sitemap

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough", "superscript"]

# Permalinks
permalink: /:title/

# Setup
name: 'Jesse Squires'
title: 'Jesse Squires'
tagline: 'Turing complete with a side of 0xdeadbeef'
timezone: America/Los_Angeles

url: http://www.jessesquires.com

author:
  name: 'Jesse Squires'
  url: https://twitter.com/jesse_squires

paginate: 4

excerpt_separator: <!--excerpt-->
